name: Check
on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_mysql
      
      - name: Install Composer
        run: composer install
      
      - name: Install Node js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: install packages
        run: npm i
      
      - name: Build assets
        run: npm run build
          
  
