name: Deploying
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_mysql
      
      - name: Install Composer
        run: composer install
      
      - name: Install Node js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: install packages
        run: npm i
      
      - name: Build assets
        run: npm run build
      
      - name: Prepare for deployment
        run:
          rm -rf node_modules
          rm -rf tests

      - name: Extract DEPLOY secrets
        run: |
          echo "${{ secrets.DEPLOY }}" | grep -E '^(SSH_|FTP_|SERVER_DIR)' | sed 's/^/export /' >> $GITHUB_ENV

      - name: Deploy to cpanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ env.FTP_SERVER }}
          username: ${{ env.FTP_USERNAME }}
          password: ${{ env.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ env.SERVER_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env.example

      - name: Run post-deployment commands via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          passphrase: ${{ env.SSH_PASSWORD }}
          key: ${{ env.SSH_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            cd ${{ env.SERVER_DIR }}
            php artisan migrate --force
            php artisan optimize
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
