name: Deploying
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check Secret Values
        run: |
          if [ "$FTP_SERVER" = "ftp.anvarcontact.uz" ]; then 
            echo "FTP_SERVER matches expected value"
          else 
            echo "FTP_SERVER does NOT match"
          fi
          
          if [ "$SSH_HOST" = "warehouse-test.xerxes.uz" ]; then 
            echo "SSH_HOST matches expected value"
          else 
            echo "SSH_HOST does NOT match"
          fi
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          SERVER_DIR: ${{ secrets.SSH_HOST }}
          
      # - name: Deploy to cpanel
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: ./
      #     server-dir: ${{ secrets.SERVER_DIR }}
      #     exclude: |
      #       **/.git*
      #       **/.git*/**
      #       **/node_modules/**
      #       .env.example
            
      # - name: Run post-deployment commands via SSH
      #   uses: appleboy/ssh-action@v1.2.1
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     password: ${{ secrets.SSH_PASSWORD }}
      #     key: ${{ secrets.SSH_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: |
      #       cd ${{ secrets.SERVER_DIR }}
      #       php artisan migrate --force
      #       php artisan optimize
      #       php artisan cache:clear
      #       php artisan config:cache
      #       php artisan route:cache
      #       php artisan view:cache
