name: Deploy 
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_mysql
      
      - name: Install Composer dependencies
        run: composer install
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install NPM dependencies
        run: npm i
      
      - name: Build assets and remove node modules
        run: |
          npm run build
          rm -rf node_modules
          
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.anvarcontact.uz
          username: github-actions@warehouse-test.xerxes.uz
          password: D^d2(c[wWjvI
          local-dir: ./
          server-dir: /home/anvarcon/warehouse-test.xerxes.uz
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env.example
      
      - name: Run post-deployment commands via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: warehouse-test.xerxes.uz
          username: anvarcon
          passphrase: D^d2(c[wWjvI
          key:
              -----BEGIN OPENSSH PRIVATE KEY-----
              b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABAIWR+bqu
              qCdNohmqxAlCDyAAAAEAAAAAEAAAEXAAAAB3NzaC1yc2EAAAADAQABAAABAQC+F+vwgJht
              fNrzz01zZ+0/yOIp/IYDcMxzHXOq+ym8ndKh8x5Dd7SN2HFAvZOgxZm+gkcbz0FP6ov36G
              T8UUfKgO9NQI8PJt+/3Gy+vTXcFL6iynrR43sri/JfqljNoeQPtA1zsihrqZrORPTSbn/8
              LAU9yfruCTyMmSgdiVppmF65ZO/Oz3GAfg9ULPly2yU9Q6gGM8/7phUPAVQnrEznkn7dcc
              E39haV7fwpUhtifhEBcy2Ho/SnZrSG+tnYE4AFwp//J8yoi6Cf2bFPA1webR6iA5JFR0Lh
              rzra0Fl7CHoZ7eX94SaxHnEdr935AZOCf7J3el/p5r5ZycrYch8jAAADwDKyfxarbxgjl7
              ul37gS4WGQnEJNUG9/ZXPlERqisH78NyunLuyZ3YGPq2b8eoCUvQ/T2j/pYQ3Q/S8NtMRq
              mx/1btYVk7XvhWwiuLWsTLOVkZlPKp0qnVmeXiYk3xyRZgu+JQXDxahGKafxYx3rVOtOi9
              yVZzywgStB5zIipMSZX6jYzha+ACLiSHPb9lKEw+V6ib4QRQ54D5t+Y5lRiOKxPf/Pcgri
              iu7zrQYWIfY9XKwQU/7OeJ0ysHHNd3ER3Y5M31wP+jt8LqhPEw4FNLT1FMsXijp/NkSFie
              jpa/AQCFQuPQBvPSYEsI5YncZ+hrtXiWYeQjVw/6NCh2A6/wsKGDAWb9J7bmPPu3ZHDTgt
              XNR3sdtZ9wQ+68TdS5CH/scs/XBq6IPYNY8t/FKFwOS/7E5r3I7K39ozfE/0nLEqKWS8aW
              7NwAfxeY/cF01r7xHv4P12eRAitJ3mUY/Vcx2PWmOaMNBB6O6mkiDFcHPdCCBzOOi1TSLR
              qGbqGjJDSD7NrNtFmTAiPpD3Eky9wgNfe+4VHUfe2cJDY3q0fxkUuI+JxykS20JIp2gMLH
              MmlzZL6/zI8PB/rKy/FFi9G9Uiskyko5p2v+tsZ7kMIxZ9nLkXzdRqUPX8PvylXB82+Nk0
              S8N/jYxOz6cvTJxopUK35sYl4PYHc/WLrolO9SYW7Zn8aVX83Y/qR3hYtlScpA16kFh70s
              1C9Y8eG1x3iaCUxGQD8v7dYSpdzE5yXUJVkun0mbmXiGLR9mqnETalIZ5h7aobjnZoxdia
              /SOpIOMvnmHb7O3sFEbyH/7KHhCoEwTFHKOJyascWG4t9/4RZnF8L4H8MUmagWc4CBlNR4
              ZTwBczMtWEaRfaDhOyBgUPOzOHOCCqcfbZVfP+Ho8vEcbxr+KWAu3VGrLdLzoOWo08Z6Ux
              OwHXIXK1lPSAFm20E6WXZSxPrC5qfjfARLy4T68cB2vj/6922ZMigMYfBhL2G950D3YAIV
              Q21hA/4uZJMKuT2yQswzh8RJajTWEjKwxS4z8kDwCqxA5V16lz7AeIy7a9hc4x+9YSXALK
              qCV67h72jyVzz1MEo10w3eRSIYqFdpAsl3l8fofhZHy/rQ1SCh9UoBCblLLUr/vyhKKcao
              02d5NRpHIZSNwRmPPI509dvHPGzvhZa8axbl2zeKifEpdubAQYRBj8mNYuzyUesmEBeOnn
              +bxKm7DhJ8HkBfv98rIRfvwVtHT9J0d1R3WhZGAccX7q37XNTbmGzl06yDhhOgEif2Aq2g
              qj4uc39g==
              -----END OPENSSH PRIVATE KEY-----
          port: 22
          script: |
            cd /home/anvarcon/warehouse-test.xerxes.uz
            php artisan migrate --force
            php artisan optimize
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
